# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/wireguard_object.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63ore/wireguard_object.proto\x12\x04\x63ore\"e\n\rWireguardNode\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\x0c\x12%\n\x04type\x18\x03 \x01(\x0e\x32\x17.core.WireguardNodeType\x12\x11\n\taddresses\x18\x04 \x03(\x0c\"R\n\x13WireguardConnection\x12\r\n\x05uuids\x18\x01 \x03(\x0c\x12\x1a\n\rpreshared_key\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\x10\n\x0e_preshared_key\"\x81\x01\n\x0fWireguardConfig\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\"\n\x05nodes\x18\x03 \x03(\x0b\x32\x13.core.WireguardNode\x12.\n\x0b\x63onnections\x18\x04 \x03(\x0b\x32\x19.core.WireguardConnection*q\n\x11WireguardNodeType\x12\x1c\n\x18WIREGUARD_NODE_TYPE_PEER\x10\x00\x12\x1e\n\x1aWIREGUARD_NODE_TYPE_ROUTER\x10\x01\x12\x1e\n\x1aWIREGUARD_NODE_TYPE_ROUTED\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.wireguard_object_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIREGUARDNODETYPE._serialized_start=356
  _WIREGUARDNODETYPE._serialized_end=469
  _WIREGUARDNODE._serialized_start=37
  _WIREGUARDNODE._serialized_end=138
  _WIREGUARDCONNECTION._serialized_start=140
  _WIREGUARDCONNECTION._serialized_end=222
  _WIREGUARDCONFIG._serialized_start=225
  _WIREGUARDCONFIG._serialized_end=354
# @@protoc_insertion_point(module_scope)
